name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
        
    - name: Run tests
      run: npm test
      
    - name: Copy files to droplet
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USERNAME }}
        key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
        source: "." # Ensure Dockerfile is included
        target: "~/app"
        rm: true # Clears existing files to prevent stale files

    - name: Deploy to Digital Ocean droplet
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USERNAME }}
        key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
        script: |
          cd ~/app
          
          # Ensure Dockerfile is present
          if [ ! -f Dockerfile ]; then
            echo "Dockerfile is missing!"
            exit 1
          fi
          
          # Build the Docker image
          docker build -t hello-wissem .
          
          # Stop and remove existing container (if exists)
          docker stop hello-wissem || true
          docker rm hello-wissem || true
          
          # Run new container
          docker run -d --name hello-wissem -p 3000:3000 hello-wissem
